# Generated by Django 2.2.5 on 2020-04-11 11:05

from django.db import migrations, models
import django.db.models.deletion
import oshop.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('parent_cat_id', models.IntegerField()),
                ('description', models.TextField()),
                ('cat_image', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'shopping-cart',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to=oshop.api.models.product_img_path)),
                ('sell_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('active', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='api.ShoppingCart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Products')),
            ],
            options={
                'db_table': 'cart-details',
            },
        ),
    ]
