# Generated by Django 2.2.5 on 2020-04-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200412_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='api.ShoppingCart'),
        ),
    ]
